project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "pankid"
  site-url: https://pankid.github.io
  favicon: images/wukong5-site.jpg
  reader-mode: true                                           # 启用阅读模式
  bread-crumbs: true                                          # 引导用户了解正在阅读的内容处于网站什么位置
  back-to-top-navigation: true                                # 页面底部加一个“返回顶部”按钮
  repo-url: https://github.com/pankid/pankid.github.io
  repo-actions: [edit, issue]
  
  page-footer: "“我们在日常生活中度过的每一天，实际上也许是连续发生的奇迹也说不定呢。”"
    #left: |
    #  [pankid](https://pankid.netlify.app)<br>
    #right: |
    #  Made with [Quarto](https://quarto.org/)<br>

  navbar: 
    background: primary
    pinned: true
    search: true
    left: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Books"
        href: books.qmd
      - text: "Blogs"
        href: blog.qmd
      - text: "Codes"
        href: codes.qmd
      - text: "中文"
        href: Chinese.qmd
      - text: "CV"
        href: about.qmd
    right: 
      - icon: github
      - text: Github
        href: https://github.com
      - icon: google
      - text: Google
        href: https://www.google.com
      - icon: youtube
      - text: YouTube
        href: https://www.youtube.com

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细