project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "pankid"
  site-url: https://pankid.github.io
  favicon: images/wukong5-site.jpg
  repo-url: https://github.com/pankid/pankid.github.io
  repo-actions: [edit, issue]
  
  page-footer: "“我们在日常生活中度过的每一天，实际上也许是连续发生的奇迹也说不定呢。”"
    #left: |
    #  [pankid](https://pankid.netlify.app)<br>
    #right: |
    #  Made with [Quarto](https://quarto.org/)<br>

  navbar: 
    background: "#87CEFA"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Books"
        href: books.qmd
      - text: "Blogs"
        href: blog.qmd
      - text: "Codes"
        href: codes.qmd
      - text: "中文"
        href: Chinese.qmd
      - text: "CV"
        href: CV.pdf

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细